# ============================================
# CONFIGURACION DEL SERVIDOR
# ============================================
server.port=8080

# ============================================
# CONFIGURACION DE LA BASE DE DATOS
# ============================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SistemaERP;encrypt=true;trustServerCertificate=true;
spring.datasource.username=erp_app
spring.datasource.password=Erp2026!Seguro
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ============================================
# CONFIGURACION DE JPA / HIBERNATE
# ============================================
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# ============================================
# LOGS
# ============================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ============================================
# THYMELEAF (Reportes HTML)
# ============================================
spring.thymeleaf.check-template-location=false

# ============================================
# JWT (Autenticacion)
# ============================================
jwt.secret=claveSecretaParaJWT2026SistemaERP
jwt.expiration=86400000